name: Manual CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install nbconvert

      - name: Convert Notebook and Train Model
        run: |
          source venv/bin/activate
          jupyter nbconvert --to script Model_training.ipynb
          python Model_training.py

      - name: Deploy Model
        run: |
          source venv/bin/activate
          nohup python app.py &

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/ngrok

      - name: Install Ngrok authentication token
        run: |
          ngrok authtoken 2gtBGRr8hapwKnpp234wYnhvyRX_2NXM8kktrkH6XYnYCpBzH

      - name: Run ngrok
        run: |
          ngrok http 5000 &

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Print ngrok URL
        run: |
          sleep 5  # Wait for ngrok to initialize
          curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
